package org.filezilla.android.data

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Encrypts and decrypts the one secret this app stores: a site's password.
 *
 * An interface because the real implementation needs the Android keystore,
 * which cannot be exercised on a plain JVM -- and the parts worth testing are
 * the database migration and the round trip through the entity, not AES.
 */
interface PasswordCipher {

    fun encrypt(plaintext: String): String

    /**
     * The plaintext, or null when the stored value cannot be read back.
     *
     * Null is a real outcome, not a defensive nicety: a keystore key is
     * destroyed when the user clears the app's data, and on some devices when
     * the screen lock is removed. The password is then gone for good, and the
     * honest response is to ask for it again -- not to crash, and not to
     * pretend the empty string was what the user typed.
     */
    fun decrypt(stored: String): String?
}

/**
 * The real one: AES-256-GCM under a key held by the Android keystore.
 *
 * The key material never leaves the keystore -- on most devices it never
 * leaves secure hardware -- so the database file alone is useless. That is the
 * property worth having: `filezilla.db` is what ends up in a backup, on a
 * recovery image, or in the hands of anyone who can read the data partition of
 * a device they have taken apart.
 *
 * What it does **not** defend against is code running as this app's own uid.
 * Anything with that can simply ask the keystore to decrypt, exactly as the
 * app does. On a rooted phone, or against malware that has already achieved
 * code execution here, these passwords are readable. Keystore raises the cost
 * of stealing the database; it does not make the secret unreadable.
 *
 * The key is *not* bound to user authentication. It has to be usable from a
 * foreground service resuming a transfer hours later with the screen locked,
 * which is the whole point of this app -- requiring a fingerprint to continue
 * a download would make the feature useless.
 */
class KeystorePasswordCipher(private val alias: String = DEFAULT_ALIAS) : PasswordCipher {

    override fun encrypt(plaintext: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key())
        val ciphertext = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
        // The IV is generated by the keystore and differs per encryption, so
        // it travels with the ciphertext. It is not a secret.
        val iv = cipher.iv
        val packed = ByteArray(1 + iv.size + ciphertext.size)
        packed[0] = iv.size.toByte()
        iv.copyInto(packed, 1)
        ciphertext.copyInto(packed, 1 + iv.size)
        return Base64.encodeToString(packed, Base64.NO_WRAP)
    }

    override fun decrypt(stored: String): String? = runCatching {
        val packed = Base64.decode(stored, Base64.NO_WRAP)
        val ivSize = packed[0].toInt()
        val iv = packed.copyOfRange(1, 1 + ivSize)
        val ciphertext = packed.copyOfRange(1 + ivSize, packed.size)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, key(), GCMParameterSpec(TAG_BITS, iv))
        String(cipher.doFinal(ciphertext), Charsets.UTF_8)
    }.getOrNull()

    private fun key(): SecretKey {
        val keystore = KeyStore.getInstance(PROVIDER).apply { load(null) }
        (keystore.getEntry(alias, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        generator.init(
            KeyGenParameterSpec.Builder(
                alias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                // A transfer resumes from a service with the screen locked, so
                // the key must be usable without the user being present.
                .setUserAuthenticationRequired(false)
                .build(),
        )
        return generator.generateKey()
    }

    private companion object {
        const val PROVIDER = "AndroidKeyStore"
        const val DEFAULT_ALIAS = "site-passwords"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val TAG_BITS = 128
    }
}
