#!/usr/bin/env python3
"""The icons the artwork does not contain, drawn to match the ones it does.

The pack has no transfers or log icon -- it is a set of things, not of
controls, and those two are the app's own ideas. They are drawn here in the
same language: a 512 viewport with roughly 56px of margin, solid fills from
the app's palette, rounded ends, no strokes, no gradients.

Kept as code rather than as hand-written XML so the geometry is stated once
and the whole set can be re-rendered when the palette moves.
"""
from __future__ import annotations

import math
import pathlib
import re

OUT = pathlib.Path("app/src/main/res/drawable")

# Claude's clay and the warm neutrals that go with it; see ui/theme/Theme.kt.
CLAY = "#C5613F"
CLAY_SOFT = "#E0A088"
CLAY_PALE = "#F6E0D6"
SLATE = "#574D45"
MIST = "#ECE5DC"
WHITE = "#FFFFFF"
# White at the alpha the pack's tiles put a background shape at.
GHOST_WHITE = "#8CFFFFFF"

# The launcher's ground, which is a gradient rather than the flat CLAY the
# rest of the app uses. A home screen is thirty icons at 48px competing for
# one glance, and a flat mid-tone is what loses that competition; the app's
# own clay is the dark end of the ramp and a brighter one lights the corner
# the mark travels towards.
CLAY_LIT = "#E07B55"

def scaled(data: str, factor: float, about: float = 256.0) -> str:
    """Shrinks path data towards the middle of the viewport.

    The launcher needs it. An adaptive icon shows only the middle two thirds
    of its canvas, and a circular mask cuts a circle out of even that -- so
    artwork drawn to the full viewport loses its corners, and an arrow that
    reaches for the top loses its head.

    Absolute coordinates move towards the centre; relative ones are only made
    smaller, because they are already distances rather than places. Treating
    the two alike is what sheared the arrows into ribbons the first time.
    """
    tokens = re.findall(r"[A-Za-z]|-?\d*\.?\d+", data)
    out: list[str] = []
    index = 0
    relative = False
    while index < len(tokens):
        token = tokens[index]
        if token.isalpha():
            relative = token.islower()
            out.append(token)
            index += 1
            continue
        pair = []
        for value in (float(token), float(tokens[index + 1])):
            pair.append(value * factor if relative else about + (value - about) * factor)
        out.append(f"{pair[0]:g},{pair[1]:g}")
        index += 2
    return re.sub(r"([A-Za-z]) ", r"\1", " ".join(out)).strip()


def rounded_rect(x: float, y: float, w: float, h: float, r: float) -> str:
    """A rounded rectangle, as vector path data."""
    return (
        f"M{x + r},{y} L{x + w - r},{y} Q{x + w},{y} {x + w},{y + r} "
        f"L{x + w},{y + h - r} Q{x + w},{y + h} {x + w - r},{y + h} "
        f"L{x + r},{y + h} Q{x},{y + h} {x},{y + h - r} "
        f"L{x},{y + r} Q{x},{y} {x + r},{y} Z"
    )


def vector(paths: list[tuple[str, str]], size: int = 24) -> str:
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by tools/icons/authored.py. Do not edit by hand. -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    xmlns:aapt="http://schemas.android.com/aapt"',
        f'    android:width="{size}dp"',
        f'    android:height="{size}dp"',
        '    android:viewportWidth="512"',
        '    android:viewportHeight="512">',
    ]
    for fill, data in paths:
        if ":" in fill:
            # A gradient, written the long way round: a vector drawable can
            # only take one as a nested attribute, not as a colour string.
            start, end = fill.split(":")
            lines += [
                "    <path",
                f'        android:pathData="{data}">',
                '        <aapt:attr name="android:fillColor">',
                '            <gradient',
                '                android:type="linear"',
                '                android:startX="0" android:startY="0"',
                '                android:endX="512" android:endY="512"',
                f'                android:startColor="{start}"',
                f'                android:endColor="{end}" />',
                "        </aapt:attr>",
                "    </path>",
            ]
        else:
            lines += ["    <path", f'        android:fillColor="{fill}"',
                      f'        android:pathData="{data}" />']
    lines += ["</vector>", ""]
    return "\n".join(lines)


# The launcher, on Android's adaptive canvas.
#
# Two tapered arrows crossing on a diagonal: one leaving, one arriving. The
# app moves things between two places, and this is that with the panes taken
# away -- the panes were accurate and inert, a pair of rectangles that said
# "some app with two lists in it" and could have been anything.
#
# Diagonal, because a mark set square sits still. Tapered, because a shaft of
# even width is a diagram of an arrow and a shaft that swells towards its head
# is an arrow that is going somewhere. The two are offset across the axis
# rather than sharing it, so the eye reads two lanes of traffic instead of one
# double-headed arrow -- which is the difference between "exchange" and
# "resize".
#
# Everything is inside the circle an adaptive mask may cut to: radius 156 from
# the middle of a 512 canvas.
TRAVEL = -35.0          # up and to the right
LANES = 52.0            # how far each lane sits off the axis


def lane(offset: float, heading: float, scale: float = 1.0) -> str:
    """One tapered arrow, offset across the line of travel.

    Thin at the tail and full at the head, ending in a solid point. The tail
    is not brought to nothing: at 48px a tail that tapers to a hair vanishes
    and the arrow turns into a floating chevron.
    """
    across = math.radians(TRAVEL + 90.0)
    cx = 256.0 + offset * scale * math.cos(across)
    cy = 256.0 + offset * scale * math.sin(across)
    a = math.radians(heading)
    ux, uy = math.cos(a), math.sin(a)
    nx, ny = -uy, ux

    length, tail, head, tip_len, tip_half = (
        v * scale for v in (240.0, 22.0, 46.0, 62.0, 48.0)
    )

    def at(along: float, out: float) -> str:
        return f"{cx + ux * along + nx * out:.1f},{cy + uy * along + ny * out:.1f}"

    back = -length / 2
    neck = length / 2 - tip_len
    points = [
        at(back, tail / 2), at(neck, head / 2), at(neck, tip_half),
        at(length / 2, 0),
        at(neck, -tip_half), at(neck, -head / 2), at(back, -tail / 2),
    ]
    return "M" + " L".join(points) + " Z"


ICONS = {
    # Transfers: the launcher's two lanes, in the palette rather than in
    # white. It was an up arrow and a down arrow standing vertically, which
    # was a perfectly good symbol and a different one from the mark on the
    # home screen -- so the app and its icon were drawn by two hands. The
    # leaving lane carries the accent.
    # 1.5 puts the tips 196 from the middle, which is the ~56px margin the
    # rest of the set is drawn to; the launcher's own copy is smaller because
    # an adaptive icon may be cut to a circle.
    "ic_flat_transfers": [
        (CLAY, lane(-LANES, TRAVEL, scale=1.5)),
        (CLAY_SOFT, lane(LANES, TRAVEL + 180.0, scale=1.5)),
    ],

    # Log: lines on a panel, the newest picked out. The last line is short,
    # which is what makes it read as a list rather than as a document.
    "ic_flat_log": [
        (MIST, rounded_rect(86, 96, 340, 320, 40)),
        (CLAY, rounded_rect(136, 152, 240, 36, 18)),
        (SLATE, rounded_rect(136, 238, 240, 36, 18)),
        (SLATE, rounded_rect(136, 324, 160, 36, 18)),
    ],
}

# The white-on-tile half of the set.
#
# Every place in the drawer wears a filled tile with a white glyph, and the
# transfer queue had no glyph of its own -- it wore a folder, which is what
# the row above it means. So the same two arrows are drawn again in white,
# the up one at the reduced alpha the pack's tiles use for the part of a
# shape that sits behind, so the pair reads as down-and-up rather than as a
# solid block.
TILES = {
    "ic_tile_transfers": [
        (WHITE, lane(-LANES, TRAVEL, scale=1.5)),
        (GHOST_WHITE, lane(LANES, TRAVEL + 180.0, scale=1.5)),
    ],
}

LAUNCHER_BACKGROUND = [(f"{CLAY_LIT}:{CLAY}", rounded_rect(0, 0, 512, 512, 0))]
LAUNCHER_FOREGROUND = [
    (WHITE, lane(-LANES, TRAVEL)),
    (WHITE, lane(LANES, TRAVEL + 180.0)),
]
# The themed-icon layer, which the system fills with one colour of its own --
# so it is the same two shapes and no ground.
LAUNCHER_MONOCHROME = [
    (WHITE, lane(-LANES, TRAVEL)),
    (WHITE, lane(LANES, TRAVEL + 180.0)),
]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, paths in ICONS.items():
        (OUT / f"{name}.xml").write_text(vector(paths))
        print(f"{name}.xml")
    for name, paths in TILES.items():
        (OUT / f"{name}.xml").write_text(vector(paths))
        print(f"{name}.xml")
    for name, paths in (
        ("ic_launcher_background", LAUNCHER_BACKGROUND),
        ("ic_launcher_foreground", LAUNCHER_FOREGROUND),
        ("ic_launcher_monochrome", LAUNCHER_MONOCHROME),
    ):
        (OUT / f"{name}.xml").write_text(vector(paths, size=108))
        print(f"{name}.xml")


if __name__ == "__main__":
    main()
