#!/usr/bin/env python3
"""The icons the artwork does not contain, drawn to match the ones it does.

The pack has no transfers or log icon -- it is a set of things, not of
controls, and those two are the app's own ideas. They are drawn here in the
same language: a 512 viewport with roughly 56px of margin, solid fills from
the app's palette, rounded ends, no strokes, no gradients.

Kept as code rather than as hand-written XML so the geometry is stated once
and the whole set can be re-rendered when the palette moves.

Needs shapely: the launcher's pieces are cut out of a folder with real
polygon arithmetic, so that the drawable carries plain paths rather than
clip-paths, which Android does not antialias.
"""
from __future__ import annotations

import math
import pathlib
import re

OUT = pathlib.Path("app/src/main/res/drawable")

# Claude's clay and the warm neutrals that go with it; see ui/theme/Theme.kt.
CLAY = "#C5613F"
CLAY_SOFT = "#E0A088"
CLAY_PALE = "#F6E0D6"
SLATE = "#574D45"
MIST = "#ECE5DC"
WHITE = "#FFFFFF"
# White at the alpha the pack's tiles put a background shape at.
GHOST_WHITE = "#8CFFFFFF"

# The launcher's ground, which is a gradient rather than the flat CLAY the
# rest of the app uses. A home screen is thirty icons at 48px competing for
# one glance, and a flat mid-tone is what loses that competition; the app's
# own clay is the dark end of the ramp and a brighter one lights the corner
# the mark travels towards.
CLAY_LIT = "#E07B55"

def scaled(data: str, factor: float, about: float = 256.0) -> str:
    """Shrinks path data towards the middle of the viewport.

    The launcher needs it. An adaptive icon shows only the middle two thirds
    of its canvas, and a circular mask cuts a circle out of even that -- so
    artwork drawn to the full viewport loses its corners, and an arrow that
    reaches for the top loses its head.

    Absolute coordinates move towards the centre; relative ones are only made
    smaller, because they are already distances rather than places. Treating
    the two alike is what sheared the arrows into ribbons the first time.
    """
    tokens = re.findall(r"[A-Za-z]|-?\d*\.?\d+", data)
    out: list[str] = []
    index = 0
    relative = False
    while index < len(tokens):
        token = tokens[index]
        if token.isalpha():
            relative = token.islower()
            out.append(token)
            index += 1
            continue
        pair = []
        for value in (float(token), float(tokens[index + 1])):
            pair.append(value * factor if relative else about + (value - about) * factor)
        out.append(f"{pair[0]:g},{pair[1]:g}")
        index += 2
    return re.sub(r"([A-Za-z]) ", r"\1", " ".join(out)).strip()


def rounded_rect(x: float, y: float, w: float, h: float, r: float) -> str:
    """A rounded rectangle, as vector path data."""
    return (
        f"M{x + r},{y} L{x + w - r},{y} Q{x + w},{y} {x + w},{y + r} "
        f"L{x + w},{y + h - r} Q{x + w},{y + h} {x + w - r},{y + h} "
        f"L{x + r},{y + h} Q{x},{y + h} {x},{y + h - r} "
        f"L{x},{y + r} Q{x},{y} {x + r},{y} Z"
    )


def vector(paths: list[tuple[str, str]], size: int = 24) -> str:
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by tools/icons/authored.py. Do not edit by hand. -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    xmlns:aapt="http://schemas.android.com/aapt"',
        f'    android:width="{size}dp"',
        f'    android:height="{size}dp"',
        '    android:viewportWidth="512"',
        '    android:viewportHeight="512">',
    ]
    for fill, data in paths:
        if ":" in fill:
            # A gradient, written the long way round: a vector drawable can
            # only take one as a nested attribute, not as a colour string.
            start, end = fill.split(":")
            lines += [
                "    <path",
                f'        android:pathData="{data}">',
                '        <aapt:attr name="android:fillColor">',
                '            <gradient',
                '                android:type="linear"',
                '                android:startX="0" android:startY="0"',
                '                android:endX="512" android:endY="512"',
                f'                android:startColor="{start}"',
                f'                android:endColor="{end}" />',
                "        </aapt:attr>",
                "    </path>",
            ]
        else:
            lines += ["    <path", f'        android:fillColor="{fill}"',
                      f'        android:pathData="{data}" />']
    lines += ["</vector>", ""]
    return "\n".join(lines)


# The launcher, on Android's adaptive canvas.
#
# A folder coming apart: the body intact and readable on the left, the far
# corner torn away into strips that fly up and to the right.
#
# The brief was a file explorer that takes the eye, drawn with the swing of
# weight a brush gives a stroke rather than the even width a vector does.
# The swing here is in the pieces: a wide body, then a strip, then a thinner
# one, then a sliver -- four weights along one tear instead of four shapes of
# the same thickness.
#
# The folder had to survive it. Earlier attempts put the energy outside the
# form -- rays spraying from an open folder, strips bowing away like wheat,
# a radial burst -- and each one read as weather happening near a folder
# rather than to it. Tearing the folder itself keeps the silhouette, which is
# the only part anybody identifies at 48px, and spends the drama on what
# happens to it.
#
# Discarded, all of which sounded right as sentences: circulating arcs (the
# refresh symbol, and a ring at small sizes), tapered darts (petals), a
# radial burst of tapered spindles -- that one is Anthropic's mark, and not
# ours to wear on somebody's home screen.
TRAVEL = -34.0                          # the line the tear runs along
CUTS = (52.0, 92.0, 114.0, 126.0)       # where along it the folder gives way
PUSHES = (0.0, 14.0, 30.0, 48.0, 70.0)  # how far each piece has got
DRIFTS = (0.0, 7.0, -5.0, 9.0, -13.0)   # and how far it has wandered across
SPINS = (0.0, 4.0, -5.0, 8.0, -11.0)    # each piece turning as it goes
RAGGED = (9.0, -7.0, 11.0, -5.0, 8.0, -10.0, 6.0)   # the zigzag of a tear
REACH = 152.0                           # the adaptive circle is 156


def _folder_outline(x, y, w, h, tab_w, tab_h, r, steps=14):
    """The folder as a closed polyline, corners sampled rather than arced.

    Flattened because the pieces are cut out with real polygon arithmetic
    below, and because a VectorDrawable clip-path -- the other way to do
    this -- is not antialiased on a good many Android versions, which would
    have put a staircase along every torn edge.
    """
    pts: list[tuple[float, float]] = []

    def corner(cx, cy, a0, a1):
        for i in range(steps + 1):
            a = math.radians(a0 + (a1 - a0) * i / steps)
            pts.append((cx + r * math.cos(a), cy + r * math.sin(a)))

    corner(x + r, y + tab_h + r, 180, 270)          # top of the tab
    pts.append((x + tab_w - 16, y + tab_h))
    pts.append((x + tab_w + 6, y))                  # the slanted shoulder
    corner(x + w - r, y + r, 270, 360)
    corner(x + w - r, y + h - r, 0, 90)
    corner(x + r, y + h - r, 90, 180)
    return pts


def _band(travel, d0, d1, ragged=None, reach=900.0):
    """The slab of the plane between d0 and d1, measured along `travel`.

    Its leading edge zigzags when `ragged` is given, which is the difference
    between a shape that was torn and a shape that was guillotined.
    """
    a = math.radians(travel)
    ux, uy = math.cos(a), math.sin(a)
    nx, ny = -uy, ux

    def at(d, s):
        return (256.0 + ux * d + nx * s, 256.0 + uy * d + ny * s)

    lead = []
    if ragged:
        n = len(ragged)
        lead.append(at(d0 + ragged[0], -reach))
        for i, jog in enumerate(ragged):
            lead.append(at(d0 + jog, -reach + 2 * reach * (i + 0.5) / n))
        lead.append(at(d0 + ragged[-1], reach))
    else:
        lead = [at(d0, -reach), at(d0, reach)]
    return lead + [at(d1, reach), at(d1, -reach)]


def _placed(poly, spin, pivot, shift):
    """One piece, turned about where it tore away and moved along its travel."""
    out = []
    c, s = math.cos(math.radians(spin)), math.sin(math.radians(spin))
    px, py = pivot
    for x, y in poly:
        rx, ry = x - px, y - py
        out.append((px + rx * c - ry * s + shift[0], py + rx * s + ry * c + shift[1]))
    return out


def torn_folder() -> list[list[tuple[float, float]]]:
    """The mark, as a list of polygons already in their final positions."""
    from shapely.geometry import Polygon
    from shapely.ops import unary_union

    whole = Polygon(_folder_outline(96, 148, 320, 216, 164, 58, 22))
    a = math.radians(TRAVEL)
    edges = (-400.0,) + CUTS + (400.0,)

    pieces = []
    for i in range(len(edges) - 1):
        slab = Polygon(_band(TRAVEL, edges[i], edges[i + 1],
                             ragged=None if i == 0 else RAGGED))
        cut = whole.intersection(slab)
        if cut.is_empty:
            continue
        pivot = (256.0 + edges[i] * math.cos(a), 256.0 + edges[i] * math.sin(a))
        shift = (PUSHES[i] * math.cos(a) - DRIFTS[i] * math.sin(a),
                 PUSHES[i] * math.sin(a) + DRIFTS[i] * math.cos(a))
        parts = cut.geoms if cut.geom_type == "MultiPolygon" else [cut]
        for part in parts:
            ring = list(part.exterior.coords)[:-1]
            if len(ring) > 2:
                pieces.append(_placed(ring, SPINS[i], pivot, shift))

    # Centred and sized from what is actually drawn: the pieces fly by
    # different amounts and the envelope is nothing the numbers above state.
    bounds = unary_union([Polygon(p) for p in pieces]).bounds
    cx, cy = (bounds[0] + bounds[2]) / 2, (bounds[1] + bounds[3]) / 2
    half = math.hypot(bounds[2] - bounds[0], bounds[3] - bounds[1]) / 2
    k = REACH / half
    return [[(256.0 + (x - cx) * k, 256.0 + (y - cy) * k) for x, y in p] for p in pieces]


def _as_path(poly) -> str:
    return "M" + " L".join(f"{x:.1f},{y:.1f}" for x, y in poly) + " Z"


# The transfers mark: two lanes on a diagonal, one leaving and one arriving.
# Its own geometry, unrelated to the launcher's tear below.
LANE_TRAVEL = -35.0     # up and to the right
LANE_OFFSET = 52.0      # how far each lane sits off the axis


def lane(offset: float, heading: float, scale: float = 1.0) -> str:
    """One tapered arrow, offset across the line of travel.

    Thin at the tail and full at the head, ending in a solid point. The tail
    is not brought to nothing: at 48px a tail that tapers to a hair vanishes
    and the arrow turns into a floating chevron.
    """
    across = math.radians(LANE_TRAVEL + 90.0)
    cx = 256.0 + offset * scale * math.cos(across)
    cy = 256.0 + offset * scale * math.sin(across)
    a = math.radians(heading)
    ux, uy = math.cos(a), math.sin(a)
    nx, ny = -uy, ux

    length, tail, head, tip_len, tip_half = (
        v * scale for v in (240.0, 22.0, 46.0, 62.0, 48.0)
    )

    def at(along: float, out: float) -> str:
        return f"{cx + ux * along + nx * out:.1f},{cy + uy * along + ny * out:.1f}"

    back = -length / 2
    neck = length / 2 - tip_len
    points = [
        at(back, tail / 2), at(neck, head / 2), at(neck, tip_half),
        at(length / 2, 0),
        at(neck, -tip_half), at(neck, -head / 2), at(back, -tail / 2),
    ]
    return "M" + " L".join(points) + " Z"


ICONS = {
    # Transfers: two lanes on a diagonal, one leaving and one arriving.
    # Drawn here rather than taken from the pack, which has no icon for a
    # queue. The leaving lane carries the accent.
    # 1.5 puts the tips 196 from the middle, which is the ~56px margin the
    # rest of the set is drawn to.
    "ic_flat_transfers": [
        (CLAY, lane(-LANE_OFFSET, LANE_TRAVEL, scale=1.5)),
        (CLAY_SOFT, lane(LANE_OFFSET, LANE_TRAVEL + 180.0, scale=1.5)),
    ],

    # Log: lines on a panel, the newest picked out. The last line is short,
    # which is what makes it read as a list rather than as a document.
    "ic_flat_log": [
        (MIST, rounded_rect(86, 96, 340, 320, 40)),
        (CLAY, rounded_rect(136, 152, 240, 36, 18)),
        (SLATE, rounded_rect(136, 238, 240, 36, 18)),
        (SLATE, rounded_rect(136, 324, 160, 36, 18)),
    ],
}

# The white-on-tile half of the set.
#
# Every place in the drawer wears a filled tile with a white glyph, and the
# transfer queue had no glyph of its own -- it wore a folder, which is what
# the row above it means. So the same two arrows are drawn again in white,
# the up one at the reduced alpha the pack's tiles use for the part of a
# shape that sits behind, so the pair reads as down-and-up rather than as a
# solid block.
TILES = {
    # The mark on the error card. Drawn here rather than taken from the pack,
    # whose warning icon is a white exclamation on an amber disc: two light
    # fills, which the tile builder's figure-from-ground rule reads as two
    # grounds and ghosts them both. A tile supplies its own disc anyway --
    # what it wants inside is the mark alone.
    "ic_tile_alert": [
        (WHITE, rounded_rect(225, 104, 62, 200, 31)),
        (WHITE, rounded_rect(218, 336, 76, 76, 38)),
    ],

    "ic_tile_transfers": [
        (WHITE, lane(-LANE_OFFSET, LANE_TRAVEL, scale=1.5)),
        (GHOST_WHITE, lane(LANE_OFFSET, LANE_TRAVEL + 180.0, scale=1.5)),
    ],
}

LAUNCHER_BACKGROUND = [(f"{CLAY_LIT}:{CLAY}", rounded_rect(0, 0, 512, 512, 0))]


def launcher_layers() -> tuple[list, list]:
    """The foreground and the themed-icon layer, which are the same shapes."""
    shapes = [(WHITE, _as_path(p)) for p in torn_folder()]
    return shapes, list(shapes)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, paths in ICONS.items():
        (OUT / f"{name}.xml").write_text(vector(paths))
        print(f"{name}.xml")
    for name, paths in TILES.items():
        (OUT / f"{name}.xml").write_text(vector(paths))
        print(f"{name}.xml")
    foreground, monochrome = launcher_layers()
    for name, paths in (
        ("ic_launcher_background", LAUNCHER_BACKGROUND),
        ("ic_launcher_foreground", foreground),
        ("ic_launcher_monochrome", monochrome),
    ):
        (OUT / f"{name}.xml").write_text(vector(paths, size=108))
        print(f"{name}.xml")


if __name__ == "__main__":
    main()
