#!/usr/bin/env python3
"""The icons the artwork does not contain, drawn to match the ones it does.

The pack has no transfers or log icon -- it is a set of things, not of
controls, and those two are the app's own ideas. They are drawn here in the
same language: a 512 viewport with roughly 56px of margin, solid fills from
the app's palette, rounded ends, no strokes, no gradients.

Kept as code rather than as hand-written XML so the geometry is stated once
and the whole set can be re-rendered when the palette moves.
"""
from __future__ import annotations

import pathlib
import re

OUT = pathlib.Path("app/src/main/res/drawable")

OCEAN = "#0B5FA5"
OCEAN_SOFT = "#7FB0DE"
OCEAN_PALE = "#D5E7F9"
SLATE = "#44505C"
MIST = "#E2E8EF"
WHITE = "#FFFFFF"

# An arrow: a shaft with a rounded tail that runs into a solid head, which is
# how the pack's own arrows are built.
ARROW_DOWN = ("M155,135 q0,-25 25,-25 q25,0 25,25 L205,300 L252,300 "
              "L180,414 L108,300 L155,300 Z")
ARROW_UP = ("M357,377 q0,25 -25,25 q-25,0 -25,-25 L307,212 L260,212 "
            "L332,98 L404,212 L357,212 Z")


def scaled(data: str, factor: float, about: float = 256.0) -> str:
    """Shrinks path data towards the middle of the viewport.

    The launcher needs it. An adaptive icon shows only the middle two thirds
    of its canvas, and a circular mask cuts a circle out of even that -- so
    artwork drawn to the full viewport loses its corners, and an arrow that
    reaches for the top loses its head.

    Absolute coordinates move towards the centre; relative ones are only made
    smaller, because they are already distances rather than places. Treating
    the two alike is what sheared the arrows into ribbons the first time.
    """
    tokens = re.findall(r"[A-Za-z]|-?\d*\.?\d+", data)
    out: list[str] = []
    index = 0
    relative = False
    while index < len(tokens):
        token = tokens[index]
        if token.isalpha():
            relative = token.islower()
            out.append(token)
            index += 1
            continue
        pair = []
        for value in (float(token), float(tokens[index + 1])):
            pair.append(value * factor if relative else about + (value - about) * factor)
        out.append(f"{pair[0]:g},{pair[1]:g}")
        index += 2
    return re.sub(r"([A-Za-z]) ", r"\1", " ".join(out)).strip()


def rounded_rect(x: float, y: float, w: float, h: float, r: float) -> str:
    """A rounded rectangle, as vector path data."""
    return (
        f"M{x + r},{y} L{x + w - r},{y} Q{x + w},{y} {x + w},{y + r} "
        f"L{x + w},{y + h - r} Q{x + w},{y + h} {x + w - r},{y + h} "
        f"L{x + r},{y + h} Q{x},{y + h} {x},{y + h - r} "
        f"L{x},{y + r} Q{x},{y} {x + r},{y} Z"
    )


def vector(paths: list[tuple[str, str]], size: int = 24) -> str:
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by tools/icons/authored.py. Do not edit by hand. -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        f'    android:width="{size}dp"',
        f'    android:height="{size}dp"',
        '    android:viewportWidth="512"',
        '    android:viewportHeight="512">',
    ]
    for fill, data in paths:
        lines += ["    <path", f'        android:fillColor="{fill}"',
                  f'        android:pathData="{data}" />']
    lines += ["</vector>", ""]
    return "\n".join(lines)


ICONS = {
    # Transfers: one arrow down, one up, the down one carrying the accent
    # because downloading is what this app is mostly used for.
    "ic_flat_transfers": [(OCEAN, ARROW_DOWN), (OCEAN_SOFT, ARROW_UP)],

    # Log: lines on a panel, the newest picked out. The last line is short,
    # which is what makes it read as a list rather than as a document.
    "ic_flat_log": [
        (MIST, rounded_rect(86, 96, 340, 320, 40)),
        (OCEAN, rounded_rect(136, 152, 240, 36, 18)),
        (SLATE, rounded_rect(136, 238, 240, 36, 18)),
        (SLATE, rounded_rect(136, 324, 160, 36, 18)),
    ],
}

# The launcher, on Android's adaptive canvas. Everything that must survive the
# system's mask stays inside the middle two thirds; the background is flat
# Ocean so the mask can cut it to any shape without losing anything.
MARK = 0.58
LAUNCHER_BACKGROUND = [(OCEAN, rounded_rect(0, 0, 512, 512, 0))]
LAUNCHER_FOREGROUND = [
    (WHITE, scaled(ARROW_DOWN, MARK)),
    (OCEAN_PALE, scaled(ARROW_UP, MARK)),
]
# The monochrome layer is a mask: the system paints it, so it is one colour.
LAUNCHER_MONOCHROME = [
    (WHITE, scaled(ARROW_DOWN, MARK)),
    (WHITE, scaled(ARROW_UP, MARK)),
]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, paths in ICONS.items():
        (OUT / f"{name}.xml").write_text(vector(paths))
        print(f"{name}.xml")
    for name, paths in (
        ("ic_launcher_background", LAUNCHER_BACKGROUND),
        ("ic_launcher_foreground", LAUNCHER_FOREGROUND),
        ("ic_launcher_monochrome", LAUNCHER_MONOCHROME),
    ):
        (OUT / f"{name}.xml").write_text(vector(paths, size=108))
        print(f"{name}.xml")


if __name__ == "__main__":
    main()
