package org.filezilla.android.storage

import android.content.Context
import java.io.File

/**
 * Where partial downloads live while they are in flight.
 *
 * App-private internal storage, not the user's chosen folder, and that is the
 * point rather than an implementation detail. Resume needs positioned writes
 * at an arbitrary offset, which a plain file supports and a Storage Access
 * Framework document may not -- a provider is free to hand back a stream that
 * only appends, or that it rewrites wholesale on close. The finished file is
 * copied into the user's folder once, at the end.
 *
 * It also keeps half a file out of the user's Downloads folder, where it would
 * look like something they could open.
 */
class PartialFiles(context: Context) {

    private val root = File(context.filesDir, "partials")

    fun forTransfer(id: String): File {
        root.mkdirs()
        // The id is generated by the app (a UUID), so it cannot contain a path
        // separator; the check is here so that stays true if it ever stops
        // being a UUID.
        require(!id.contains('/') && !id.contains("..")) { "unsafe transfer id: $id" }
        return File(root, "$id.part")
    }

    fun delete(id: String) {
        forTransfer(id).delete()
    }

    /** Length of the partial file, or null when there is none. */
    fun sizeOf(id: String): Long? = forTransfer(id).takeIf { it.isFile }?.length()

    /**
     * Removes partial files that no live transfer claims.
     *
     * Without this a cancelled transfer whose record was deleted -- or one
     * interrupted by a crash between writing the file and writing the journal
     * -- would keep its bytes on internal storage forever.
     */
    fun pruneOrphans(liveIds: Set<String>) {
        val files = root.listFiles() ?: return
        for (file in files) {
            val id = file.name.removeSuffix(".part")
            if (id !in liveIds) file.delete()
        }
    }
}
